name: Publish to YouTube

on:
  schedule:
    - cron: "0 10 * * *"   # todos os dias 10:00 UTC
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ffmpeg + fonts (drawtext)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fontconfig fonts-dejavu-core curl tar

      # =========================
      # Install Piper (offline TTS)
      # ======================== - name: Install Piper (offline TTS)

      - name: Install Piper (offline TTS)
        run: |
          set -euxo pipefail
          mkdir -p piper
          cd piper

          LATEST_URL=$(curl -s https://api.github.com/repos/rhasspy/piper/releases/latest | \
          grep browser_download_url | \
          grep piper_linux_x86_64.tar.gz | \
          cut -d '"' -f 4)

          echo "Downloading: $LATEST_URL"
          curl -fL --retry 5 --retry-delay 2 -o piper_linux_x86_64.tar.gz "$LATEST_URL"

          tar -xzf piper_linux_x86_64.tar.gz
          ls -lah

          # find the binary (works even if folder structure changes)
          PIPER_BIN=$(find . -type f -name piper -perm -111 | head -n 1)
          echo "PIPER_BIN=$PIPER_BIN"
          "$PIPER_BIN" --help | head -n 20
    
  

      # =========================
      # Download Piper voice
      # =========================
      - name: Download Piper voice (en_US)
        run: |
          set -euxo pipefail
          mkdir -p voices
          cd voices

          curl -fL --retry 5 --retry-delay 2 -o en_US-lessac-medium.onnx \
            https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx

          curl -fL --retry 5 --retry-delay 2 -o en_US-lessac-medium.onnx.json \
            https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx.json

          ls -lah

      - name: Write OAuth secret to file
        run: |
          echo '${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}' > client_secret.json

      - name: Decide video mode (short daily, long on Saturday)
        run: |
          if [ "$(date -u +%u)" = "6" ]; then
            echo "Saturday => long"
            echo "VIDEO_MODE=long" >> $GITHUB_ENV
          else
            echo "Daily => short"
            echo "VIDEO_MODE=short" >> $GITHUB_ENV
          fi

      - name: Generate video
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python scripts/generate_video.py

      - name: Upload to YouTube
        env:
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: python scripts/upload_youtube.py
